type FeatureKind = "notes" | "projects" | "resources" | "calendar" | "tasks" | "search" | "sync";

type Feature = {
  mark: string;
  title: string;
  description: string;
  kind: FeatureKind;
  className: string;
};

const features: Feature[] = [
  { mark: "01", title: "Smart notes", description: "Keep ideas, sources, and next steps together while you think.", kind: "notes", className: "lg:col-span-7 lg:row-span-2 lg:min-h-[480px]" },
  { mark: "02", title: "Projects that stay clear", description: "See the work moving forward without losing the surrounding context.", kind: "projects", className: "lg:col-span-5 lg:min-h-[232px]" },
  { mark: "03", title: "A library worth using", description: "Save important resources in a place you will actually revisit.", kind: "resources", className: "lg:col-span-5 lg:min-h-[232px]" },
  { mark: "04", title: "Time in context", description: "Plan the week around the work that needs your attention.", kind: "calendar", className: "lg:col-span-4" },
  { mark: "05", title: "A focused task list", description: "Keep the next action visible and the noise out of sight.", kind: "tasks", className: "lg:col-span-4" },
  { mark: "06", title: "Find what matters", description: "Bring the right note, resource, or project back in seconds.", kind: "search", className: "lg:col-span-4" },
  { mark: "07", title: "Connected by default", description: "Your work stays organized together, wherever you return to it.", kind: "sync", className: "lg:col-span-12" },
];

function FeatureVisual({ kind }: { kind: FeatureKind }) {
  if (kind === "notes") return <div className="mt-8 rounded-lg border border-white/8 bg-zinc-950/70 p-4 sm:mt-12 sm:p-5"><div className="flex items-center justify-between border-b border-white/8 pb-3"><span className="text-[10px] font-semibold tracking-[0.12em] text-yellow-500">CELL BIOLOGY</span><span className="text-[10px] text-zinc-600">Edited now</span></div><p className="mt-5 text-sm font-medium text-zinc-200">The membrane is selectively permeable.</p><div className="mt-4 space-y-2"><span className="block h-2 w-full rounded bg-zinc-800" /><span className="block h-2 w-11/12 rounded bg-zinc-800" /><span className="block h-2 w-4/6 rounded bg-zinc-800" /></div><div className="mt-6 flex gap-2"><span className="rounded bg-yellow-500/10 px-2 py-1 text-[10px] text-yellow-400">Lecture PDF</span><span className="rounded bg-zinc-900 px-2 py-1 text-[10px] text-zinc-500">Study task</span></div></div>;
  if (kind === "projects") return <div className="mt-7 grid grid-cols-3 gap-2"><div className="rounded bg-zinc-950/70 p-2"><span className="text-[9px] text-zinc-600">PLAN</span><span className="mt-3 block h-8 rounded border border-white/8 bg-zinc-900" /></div><div className="rounded bg-zinc-950/70 p-2"><span className="text-[9px] text-zinc-600">DOING</span><span className="mt-3 block h-12 rounded border border-yellow-500/20 bg-yellow-500/10" /></div><div className="rounded bg-zinc-950/70 p-2"><span className="text-[9px] text-zinc-600">DONE</span><span className="mt-3 block h-6 rounded border border-white/8 bg-zinc-900" /></div></div>;
  if (kind === "resources") return <div className="mt-7 space-y-2"><div className="flex items-center justify-between rounded-md border border-white/8 bg-zinc-950/70 px-3 py-2"><span className="text-[10px] text-zinc-300">Lecture notes.pdf</span><span className="text-[9px] text-yellow-500">PDF</span></div><div className="flex items-center justify-between rounded-md border border-white/8 bg-zinc-950/70 px-3 py-2"><span className="text-[10px] text-zinc-300">Research article</span><span className="text-[9px] text-zinc-500">LINK</span></div><div className="flex items-center justify-between rounded-md border border-white/8 bg-zinc-950/70 px-3 py-2"><span className="text-[10px] text-zinc-300">Revision guide</span><span className="text-[9px] text-zinc-500">NOTE</span></div></div>;
  if (kind === "calendar") return <div className="mt-7 grid grid-cols-5 gap-1.5">{["M", "T", "W", "T", "F"].map((day, index) => <span key={`${day}-${index}`} className={`rounded p-2 text-center text-[10px] ${index === 1 ? "bg-yellow-500 text-zinc-950" : "bg-zinc-950/70 text-zinc-500"}`}>{day}</span>)}</div>;
  if (kind === "tasks") return <div className="mt-7 space-y-2.5">{["Review source material", "Outline the report", "Schedule revision"].map((task, index) => <div key={task} className="flex items-center gap-2"><span className={`grid size-4 place-items-center rounded border text-[9px] ${index === 0 ? "border-yellow-500 bg-yellow-500 text-zinc-950" : "border-zinc-700 text-transparent"}`}>✓</span><span className={`text-[10px] ${index === 0 ? "text-zinc-500 line-through" : "text-zinc-300"}`}>{task}</span></div>)}</div>;
  if (kind === "search") return <div className="mt-7 rounded-md border border-yellow-500/25 bg-zinc-950/70 p-2"><div className="flex items-center gap-2 rounded bg-zinc-900 px-2.5 py-2"><span className="text-xs text-yellow-500">⌕</span><span className="text-[10px] text-zinc-400">cell membrane</span></div><div className="mt-2 space-y-1.5"><span className="block rounded bg-zinc-900 px-2 py-1.5 text-[9px] text-zinc-500">Notes · Cell biology</span><span className="block rounded bg-zinc-900 px-2 py-1.5 text-[9px] text-zinc-500">Resources · Lecture PDF</span></div></div>;
  return <div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="rounded-md border border-white/8 bg-zinc-950/70 p-3"><span className="block h-2 w-2/3 rounded bg-zinc-700" /><span className="mt-2 block h-2 w-full rounded bg-zinc-800" /></div><span className="text-yellow-500">↔</span><div className="rounded-md border border-yellow-500/20 bg-yellow-500/[0.06] p-3"><span className="block h-2 w-2/3 rounded bg-yellow-500/50" /><span className="mt-2 block h-2 w-full rounded bg-yellow-500/20" /></div></div>;
}

function FeatureCard({ feature }: { feature: Feature }) {
  return <article className={`${feature.className} group flex min-h-[220px] flex-col overflow-hidden rounded-xl border border-white/10 bg-zinc-900/65 p-5 transition duration-300 hover:-translate-y-1 hover:border-yellow-500/30 hover:bg-zinc-900 sm:p-6`}><div className="flex items-center justify-between"><span className="text-[10px] font-semibold tracking-[0.14em] text-yellow-500">{feature.mark}</span><span className="grid size-6 place-items-center rounded border border-white/10 text-[9px] font-medium text-zinc-500 transition group-hover:border-yellow-500/30 group-hover:text-yellow-400">A</span></div><h3 className="mt-5 text-lg font-semibold tracking-tight text-zinc-100">{feature.title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-zinc-500">{feature.description}</p><div className="mt-auto"><FeatureVisual kind={feature.kind} /></div></article>;
}

export default function CoreFeatures() {
  return <section id="features" aria-labelledby="features-heading" className="bg-zinc-950 px-5 py-20 text-white sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><header className="flex max-w-2xl flex-col items-start"><span className="inline-flex rounded-full border border-yellow-500/25 bg-yellow-500/[0.07] px-3 py-1.5 text-xs font-medium tracking-[0.14em] text-yellow-400">CORE CAPABILITIES</span><h2 id="features-heading" className="mt-5 text-balance text-3xl font-semibold tracking-[-0.045em] text-white sm:text-4xl lg:text-5xl">Everything you need to keep work moving.</h2><p className="mt-5 text-pretty text-base leading-7 text-zinc-400">A considered set of tools for collecting knowledge, planning your time, and following through—without creating another system to maintain.</p></header><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-12 lg:gap-5">{features.map((feature) => <FeatureCard key={feature.title} feature={feature} />)}</div></div></section>;
}
