"use client";

import { useId, useState } from "react";

type ExperiencePanel = {
  id: "workspace" | "notes" | "projects" | "resources" | "tasks" | "calendar" | "settings";
  label: string;
  eyebrow: string;
  title: string;
  description: string;
};

const panels: ExperiencePanel[] = [
  { id: "workspace", label: "Workspace", eyebrow: "YOUR DAY, IN CONTEXT", title: "Start with what matters.", description: "A clear view of your focus, upcoming time, and the work already connected to it." },
  { id: "notes", label: "Notes", eyebrow: "A PLACE TO THINK", title: "Keep the thread of an idea.", description: "Write freely while the relevant sources and next steps stay within reach." },
  { id: "projects", label: "Projects", eyebrow: "WORK, MOVING FORWARD", title: "See progress without the noise.", description: "A calmer way to hold the moving parts of work that takes more than one sitting." },
  { id: "resources", label: "Resources", eyebrow: "READY WHEN YOU NEED IT", title: "Build a library with a memory.", description: "Save material once, then return to it in the context where it is useful." },
  { id: "tasks", label: "Tasks", eyebrow: "ONE NEXT STEP", title: "Keep attention on the work ahead.", description: "Turn the right thought into the next action without creating another list to manage." },
  { id: "calendar", label: "Calendar", eyebrow: "TIME WITH A PURPOSE", title: "Plan around your real work.", description: "A simple weekly rhythm that keeps deadlines and preparation in the same view." },
  { id: "settings", label: "Settings", eyebrow: "MADE TO FEEL YOURS", title: "A workspace that stays out of the way.", description: "Shape the environment around how you work, not the other way around." },
];

function AppChrome({ children, title }: { children: React.ReactNode; title: string }) {
  return <div className="overflow-hidden rounded-xl border border-white/10 bg-zinc-900 p-2 shadow-[0_28px_80px_rgba(0,0,0,0.42)]"><div className="flex items-center border-b border-white/8 px-3 py-2.5"><div className="flex gap-1.5" aria-hidden="true"><span className="size-1.5 rounded-full bg-zinc-600" /><span className="size-1.5 rounded-full bg-zinc-600" /><span className="size-1.5 rounded-full bg-zinc-600" /></div><span className="mx-auto text-[10px] font-semibold tracking-[0.16em] text-yellow-500">ATLAS</span><span className="w-7" /></div><div className="grid min-h-[360px] grid-cols-[92px_1fr] sm:min-h-[430px] sm:grid-cols-[122px_1fr]"><aside className="border-r border-white/8 p-3 sm:p-4"><span className="grid size-5 place-items-center rounded bg-yellow-500 text-[10px] font-bold text-zinc-950">A</span><p className="mt-7 text-[9px] font-semibold tracking-[0.15em] text-zinc-600">ATLAS</p><span className="mt-3 block rounded-md bg-yellow-500/10 px-2 py-1.5 text-[10px] text-yellow-400">{title}</span><span className="mt-1 block px-2 py-1.5 text-[10px] text-zinc-600">Library</span><span className="mt-1 block px-2 py-1.5 text-[10px] text-zinc-600">Personal</span></aside><div className="min-w-0 p-4 sm:p-6">{children}</div></div></div>;
}

function Preview({ panel }: { panel: ExperiencePanel }) {
  const title = panel.label;
  const sharedHeader = <header><p className="text-[10px] font-medium tracking-[0.12em] text-zinc-500">{panel.eyebrow}</p><h3 className="mt-1 text-lg font-semibold tracking-tight text-white sm:text-2xl">{panel.title}</h3></header>;
  let content: React.ReactNode;
  if (panel.id === "notes") content = <><div className="mt-7 flex items-center justify-between border-b border-white/8 pb-3"><span className="text-[10px] font-semibold text-yellow-500">CELL BIOLOGY</span><span className="text-[10px] text-zinc-600">Edited now</span></div><p className="mt-6 text-sm font-medium text-zinc-200">The membrane is selectively permeable, allowing the cell to maintain the conditions it needs.</p><div className="mt-5 space-y-2"><span className="block h-2 w-full rounded bg-zinc-800" /><span className="block h-2 w-11/12 rounded bg-zinc-800" /><span className="block h-2 w-3/4 rounded bg-zinc-800" /></div><div className="mt-7 flex flex-wrap gap-2"><span className="rounded bg-yellow-500/10 px-2 py-1 text-[10px] text-yellow-400">Lecture PDF</span><span className="rounded bg-zinc-900 px-2 py-1 text-[10px] text-zinc-500">Revision task</span></div></>;
  else if (panel.id === "projects") content = <><div className="mt-7 grid grid-cols-3 gap-2"><div><span className="text-[9px] text-zinc-600">PLAN</span><div className="mt-2 space-y-2"><span className="block h-12 rounded border border-white/8 bg-zinc-950/70" /><span className="block h-8 rounded border border-white/8 bg-zinc-950/70" /></div></div><div><span className="text-[9px] text-zinc-600">DOING</span><div className="mt-2 space-y-2"><span className="block h-16 rounded border border-yellow-500/25 bg-yellow-500/[0.08]" /></div></div><div><span className="text-[9px] text-zinc-600">COMPLETE</span><div className="mt-2 space-y-2"><span className="block h-10 rounded border border-white/8 bg-zinc-950/70" /></div></div></div><p className="mt-6 text-xs text-zinc-500">Research report · 4 items moving</p></>;
  else if (panel.id === "resources") content = <><div className="mt-7 space-y-2">{[["Lecture notes.pdf", "PDF"], ["Cell signalling study", "LINK"], ["Revision questions", "NOTE"], ["Lab methods", "PDF"]].map(([name, type]) => <div key={name} className="flex items-center justify-between rounded-lg border border-white/8 bg-zinc-950/70 px-3 py-3"><span className="text-xs text-zinc-300">{name}</span><span className="text-[9px] font-medium text-yellow-500">{type}</span></div>)}</div></>;
  else if (panel.id === "tasks") content = <><div className="mt-7 space-y-3">{[["Review the seminar sources", true], ["Complete biology summary", false], ["Plan Thursday revision", false], ["Send project outline", false]].map(([task, done]) => <div key={String(task)} className="flex items-center gap-3 rounded-lg border border-white/8 bg-zinc-950/70 px-3 py-3"><span className={`grid size-4 place-items-center rounded border text-[9px] ${done ? "border-yellow-500 bg-yellow-500 text-zinc-950" : "border-zinc-700 text-transparent"}`}>✓</span><span className={`text-xs ${done ? "text-zinc-600 line-through" : "text-zinc-300"}`}>{task}</span></div>)}</div></>;
  else if (panel.id === "calendar") content = <><div className="mt-7 grid grid-cols-5 gap-1.5">{["MON", "TUE", "WED", "THU", "FRI"].map((day, index) => <div key={day} className="min-h-40 rounded-lg border border-white/8 bg-zinc-950/70 p-2"><span className={`grid size-5 place-items-center rounded text-[9px] ${index === 1 ? "bg-yellow-500 font-semibold text-zinc-950" : "text-zinc-500"}`}>{day.slice(0, 1)}</span>{index === 1 && <span className="mt-5 block rounded bg-yellow-500/15 px-1 py-2 text-[8px] text-yellow-400">Study block</span>}{index === 3 && <span className="mt-9 block rounded bg-zinc-800 px-1 py-2 text-[8px] text-zinc-400">Seminar</span>}</div>)}</div></>;
  else if (panel.id === "settings") content = <><div className="mt-7 space-y-3">{["Appearance", "Notifications", "Workspace preferences"].map((setting, index) => <div key={setting} className="flex items-center justify-between rounded-lg border border-white/8 bg-zinc-950/70 px-3 py-3"><span className="text-xs text-zinc-300">{setting}</span><span className={`relative h-4 w-7 rounded-full ${index === 0 ? "bg-yellow-500" : "bg-zinc-700"}`}><span className={`absolute top-0.5 size-3 rounded-full bg-white ${index === 0 ? "right-0.5" : "left-0.5"}`} /></span></div>)}</div></>;
  else content = <><div className="mt-7 grid gap-3 sm:grid-cols-[1.2fr_.8fr]"><article className="rounded-lg border border-yellow-500/20 bg-zinc-950/70 p-4"><span className="text-[10px] font-semibold tracking-[0.12em] text-yellow-500">FOCUS</span><p className="mt-4 text-xs font-semibold text-zinc-200">Complete biology revision notes</p><div className="mt-5 h-1.5 rounded-full bg-zinc-800"><div className="h-full w-2/3 rounded-full bg-yellow-500" /></div></article><article className="rounded-lg border border-white/8 bg-zinc-950/70 p-4"><span className="text-[10px] text-zinc-500">UP NEXT</span><p className="mt-4 text-xs text-zinc-200">Research seminar</p><p className="mt-1 text-[10px] text-zinc-500">Tomorrow · 10:30</p></article></div><div className="mt-3 rounded-lg border border-white/8 bg-zinc-950/70 p-4"><span className="text-[10px] text-zinc-500">RECENTLY CONNECTED</span><div className="mt-3 grid grid-cols-3 gap-2"><span className="rounded bg-zinc-900 p-2 text-[10px] text-zinc-400">Notes</span><span className="rounded bg-zinc-900 p-2 text-[10px] text-zinc-400">Sources</span><span className="rounded bg-zinc-900 p-2 text-[10px] text-zinc-400">Tasks</span></div></div></>;
  return <AppChrome title={title}><div key={panel.id} className="motion-safe:animate-atlas-preview-swap">{sharedHeader}{content}</div></AppChrome>;
}

export default function ExperienceAtlas() {
  const [activeId, setActiveId] = useState<ExperiencePanel["id"]>("workspace");
  const tabListId = useId();
  const active = panels.find((panel) => panel.id === activeId) ?? panels[0];
  return <section id="experience" aria-labelledby="experience-heading" className="border-t border-white/8 bg-zinc-950 px-5 py-20 text-white sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><header className="mx-auto max-w-2xl text-center"><span className="inline-flex rounded-full border border-yellow-500/25 bg-yellow-500/[0.07] px-3 py-1.5 text-xs font-medium tracking-[0.14em] text-yellow-400">EXPERIENCE ATLAS</span><h2 id="experience-heading" className="mt-5 text-balance text-3xl font-semibold tracking-[-0.045em] sm:text-4xl lg:text-5xl">A workspace that feels familiar from the first day.</h2><p className="mt-5 text-pretty text-base leading-7 text-zinc-400">Move through your work the way you naturally think about it. Each space is clear on its own and connected when it matters.</p></header><div className="mt-12 grid gap-7 lg:grid-cols-[260px_1fr] lg:gap-12"><div><div role="tablist" aria-label="Explore Atlas" className="flex gap-2 overflow-x-auto pb-2 lg:flex-col lg:overflow-visible">{panels.map((panel) => <button key={panel.id} id={`${tabListId}-${panel.id}`} type="button" role="tab" aria-selected={active.id === panel.id} aria-controls={`${tabListId}-preview`} onClick={() => setActiveId(panel.id)} className={`shrink-0 rounded-lg border px-3 py-2.5 text-left text-sm transition ${active.id === panel.id ? "border-yellow-500/25 bg-yellow-500/[0.09] text-yellow-400" : "border-transparent text-zinc-500 hover:border-white/10 hover:bg-white/[0.03] hover:text-zinc-200"}`}>{panel.label}</button>)}</div><div className="mt-7 hidden border-l border-yellow-500/40 pl-4 lg:block"><p className="text-xs font-semibold text-zinc-200">{active.title}</p><p className="mt-2 text-sm leading-6 text-zinc-500">{active.description}</p></div></div><div id={`${tabListId}-preview`} role="tabpanel" aria-labelledby={`${tabListId}-${active.id}`}><Preview panel={active} /></div></div><p className="mx-auto mt-7 max-w-xl text-center text-sm leading-6 text-zinc-500 lg:hidden">{active.description}</p></div></section>;
}
